
/**************************************************************
 *	
 *	cheatBGM, 8 bit, 11025Hz,
 *	1 channel, 2537280 bytes/channel
 *	Total Size: 1 * 2537280 + 4 (header) = 2537324 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sam\Downloads\M04_SeminChoi\cheatBGM.wav
 *	Time-stamp: Mon Dec 03 22:34:41 2018
 *	
 **************************************************************/

#ifndef __CHEATBGMH__
#define __CHEATBGMH__

#define CHEATBGMFREQ 11025
#define CHEATBGMLEN 2537280

extern const unsigned char cheatBGM[2537280];

#endif /* __CHEATBGMH__ */
