
/**************************************************************
 *	
 *	loseBGM, 8 bit, 11025Hz,
 *	1 channel, 85248 bytes/channel
 *	Total Size: 1 * 85248 + 4 (header) = 85292 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sam\Downloads\M03_SeminChoi-2\loseBGM.wav
 *	Time-stamp: Thu Nov 29 15:10:24 2018
 *	
 **************************************************************/

#ifndef __LOSEBGMH__
#define __LOSEBGMH__

#define LOSEBGMFREQ 11025
#define LOSEBGMLEN 85248

extern const unsigned char loseBGM[85248];

#endif /* __LOSEBGMH__ */
