
/**************************************************************
 *	
 *	startBGM, 8 bit, 11025Hz,
 *	1 channel, 628416 bytes/channel
 *	Total Size: 1 * 628416 + 4 (header) = 628460 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sam\Downloads\M03_SeminChoi-2\startBGM.wav
 *	Time-stamp: Thu Nov 29 15:33:55 2018
 *	
 **************************************************************/

#ifndef __STARTBGMH__
#define __STARTBGMH__

#define STARTBGMFREQ 11025
#define STARTBGMLEN 628416

extern const unsigned char startBGM[628416];

#endif /* __STARTBGMH__ */
