
/**************************************************************
 *	
 *	thriller8bit, 8 bit, 11025Hz,
 *	1 channel, 1630329 bytes/channel
 *	Total Size: 1 * 1630329 + 4 (header) = 1630373 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sam\Downloads\M03_SeminChoi-2\thriller8bit.wav
 *	Time-stamp: Thu Nov 29 14:35:28 2018
 *	
 **************************************************************/

#ifndef __THRILLER8BITH__
#define __THRILLER8BITH__

#define THRILLER8BITFREQ 11025
#define THRILLER8BITLEN 1630329

extern const unsigned char thriller8bit[1630329];

#endif /* __THRILLER8BITH__ */
