
/**************************************************************
 *	
 *	zombiedeath, 8 bit, 11025Hz,
 *	1 channel, 7805 bytes/channel
 *	Total Size: 1 * 7805 + 4 (header) = 7849 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sam\Downloads\M03_SeminChoi-2\zombiedeath.wav
 *	Time-stamp: Thu Nov 29 15:29:24 2018
 *	
 **************************************************************/

#ifndef __ZOMBIEDEATHH__
#define __ZOMBIEDEATHH__

#define ZOMBIEDEATHFREQ 11025
#define ZOMBIEDEATHLEN 7805

extern const unsigned char zombiedeath[7805];

#endif /* __ZOMBIEDEATHH__ */
